name: Last Update Repo

env:
  UPDATE_FILE: last_update_repo
  PR_BRANCH: bot-workflow-active
  PR_BASE: main

on:
  schedule:
    - cron: '0 2 * * *'
  workflow_dispatch:

jobs:
  update-date:
    runs-on: ubuntu-latest
    continue-on-error: false
    timeout-minutes: 10
    environment: prod
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: write    # This is required for updating user definitions
      pull-requests: write # This is required for opening PR

    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11

      - name: Set current date
        run: echo "DATE=$(date -u +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV

      - name: Update last_update_repo file
        shell: bash
        run: |
          echo "${{ env.DATE }}" > $UPDATE_FILE

      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          set -e

          # closing existing pr
          if [ $(gh pr list --head $PR_BRANCH | wc -l) != "0" ]; then
            echo "closing existing PR on branch $PR_BRANCH"
            gh pr close $PR_BRANCH -d
          fi

          git fetch --all
          # delete branch if still exist (otherwise no error)
          git push --delete origin $PR_BRANCH || true
          # create branch and push disabled users file
          git checkout -b $PR_BRANCH origin/$PR_BASE
          git add $UPDATE_FILE
          git config user.name github-actions
          git config user.email github-actions@github.com
          git commit -m "chore: Last Update Repo changed"
          git push --set-upstream origin $PR_BRANCH

          # create pr
          gh pr create \
            --head $PR_BRANCH \
            --base $PR_BASE \
            --title "Last Update Repo changed" \
            --body "Update Repo with date ${{ env.DATE }}"
