name: AKS Scheduler

on:
  schedule:
    - cron: '0 20 * * 1-5' # 8 PM
    - cron: '0 8 * * 1-5'  # 8 AM

jobs:
  manage-aks:
    runs-on: "ubuntu-22.04"
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        
      - name: Login to Azure
        uses: azure/login@a65d910e8af852a8061c627c456678983e180302
        with:
          client-id: ${{ secrets.AZ_CLIENT_ID }}
          tenant-id: ${{ secrets.AZ_TENANT_ID }}
          subscription-id: ${{ secrets.AZ_SUBSCRIPTION_ID }}

      - name: List AKS clusters and resource groups
        id: get-clusters
        run: |
          clusters_and_rgs=$(az aks list --query "[].{name:name, resourceGroup:resourceGroup}" -o tsv)
          echo "clusters_and_rgs=${clusters_and_rgs}" >> $GITHUB_ENV

      - name: Stop AKS clusters
        if: ${{ github.event.schedule == '0 20 * * *' }}
        run: |
          IFS=$'\n'
          for cluster_rg in ${{ env.clusters_and_rgs }}
          do
            cluster=$(echo ${cluster_rg} | awk '{print $1}')
            rg=$(echo ${cluster_rg} | awk '{print $2}')
            az aks stop --resource-group ${rg} --name ${cluster}
          done

      - name: Start AKS clusters
        if: ${{ github.event.schedule == '0 8 * * *' }}
        run: |
          IFS=$'\n'
          for cluster_rg in ${{ env.clusters_and_rgs }}
          do
            cluster=$(echo ${cluster_rg} | awk '{print $1}')
            rg=$(echo ${cluster_rg} | awk '{print $2}')
            az aks start --resource-group ${rg} --name ${cluster}
          done